from _typeshed import MaybeNone
from collections.abc import Callable, Iterable
from contextlib import AbstractContextManager
from tkinter import Event
from tkinter.ttk import _TreeviewItemDict
from typing import Any, Literal, TypedDict, overload

from typing_extensions import Self
import customtkinter as ctk

from .types import Anchor, Color, FontDescription, ImageSpec, ScreenUnits

class _TreeviewTagDict(TypedDict):
    # There is also 'text' and 'anchor', but they don't seem to do anything, using them is likely a bug
    foreground: str
    background: str
    font: FontDescription
    image: str  # not wrapped in list :D

class Headings(AbstractContextManager):
    def __init__(self, obj: CTkTreeview) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
    def anchor(self, column: str | int, anchor: Anchor) -> None: ...
    @overload
    def command(self, column: str | int, command: str | Callable[[], None]) -> None: ...
    @overload
    def command(self, column: str | int) -> str | Callable[[], None]: ...
    @overload
    def image(self, column: str | int, image: ImageSpec) -> None: ...
    @overload
    def image(self, column: str | int) -> ImageSpec: ...
    @overload
    def text(self, column: str | int, text: str) -> None: ...
    @overload
    def text(self, column: str | int) -> str: ...

class Columns(AbstractContextManager):
    """
    A context manager that sets options for the headings.
    """
    def __init__(self, obj: CTkTreeview) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...
    @overload
    def anchor(self, column: int | str, anchor: Anchor) -> None: ...
    @overload
    def anchor(self, column: int | str) -> Anchor: ...
    def id(self, column: int | str) -> str: ...
    @overload
    def minwidth(self, column: int | str) -> int: ...
    @overload
    def minwidth(self, column: int | str, minwidth: int) -> None: ...
    @overload
    def width(self, column: int | str) -> int: ...
    @overload
    def width(self, column: int | str, width: int) -> None: ...
    @overload
    def stretch(self, column: int | str, stretch: bool) -> None: ...
    @overload
    def stretch(self, column: int | str) -> bool: ...

class CTkTreeview(ctk.CTkFrame):
    """
    A customized treeview widget.

    For the time being, no customizations are done on this
    widget---such changes will be done at a later update.
    """

    _valid_frame_options = ...
    def __init__(
        self,
        master: Any,
        *,
        columns: str | Iterable[str | int],
        displaycolumns: str | int | Iterable[str] | Iterable[int] = ...,
        height: int = ...,
        selectmode: Literal["browse", "extended", "none"] = ...,
        show: Literal["tree", "headings", "tree headings", ""] | Iterable[str] = ...,
        bg_color: Color = ...,
        border_color: Color | None = ...,
        border_width: int | str | None = ...,
        corner_radius: int | str | None = ...,
        fg_color: Color | None = ...,
        width: int = ...,
        **kw,
    ) -> None: ...
    def columns(self) -> Columns: ...
    def configure(self, require_redraw=..., **kw) -> None: ...
    def headings(self) -> Headings: ...

    ## Treeview wrapper methods

    def bbox(
        self, item: str | int, column: str | int | None = ...
    ) -> tuple[int, int, int, int] | Literal[""]: ...
    def delete(self, *items: str | int) -> None: ...
    def detach(self, *items: str | int) -> None: ...
    def exists(self, item: str | int) -> bool: ...
    @overload
    def focus(self, item: None = None) -> str: ...
    @overload
    def focus(self, item: str | int) -> Literal[""]: ...
    def get_children(self, item: str | int | None = None) -> tuple[str, ...]: ...
    def identify(self, component, x, y): ...
    def identify_element(self, x: int, y: int) -> str: ...
    def identify_column(self, x: int) -> str: ...
    def identify_region(
        self, x: int, y: int
    ) -> Literal["cell", "heading", "nothing", "separator", "tree"]: ...
    def identify_row(self, y: int) -> str: ...
    def index(self, item: str | int) -> int: ...
    def insert(
        self,
        parent: str,
        index: int | Literal["end"],
        iid: str | int = ...,
        *,
        id: str | int = ...,
        text: str = ...,
        image: ImageSpec = ...,
        values: list[Any] | tuple[Any, ...] = ...,
        open: bool = ...,
        tags: str | list[str] | tuple[str, ...] = ...,
    ) -> str: ...
    @overload
    def item(self, item: str | int, option: Literal["text"]) -> str: ...
    @overload
    def item(
        self, item: str | int, option: Literal["image"]
    ) -> tuple[str] | Literal[""]: ...
    @overload
    def item(
        self, item: str | int, option: Literal["values"]
    ) -> tuple[Any, ...] | Literal[""]: ...
    @overload
    def item(self, item: str | int, option: Literal["open"]) -> bool: ...
    @overload
    def item(
        self, item: str | int, option: Literal["tags"]
    ) -> tuple[str, ...] | Literal[""]: ...
    @overload
    def item(self, item: str | int, option: str) -> Any: ...
    @overload
    def item(self, item: str | int) -> _TreeviewItemDict: ...
    @overload
    def item(
        self,
        item: str | int,
        option: None = None,
        *,
        text: str = ...,
        image: ImageSpec = ...,
        values: list[Any] | tuple[Any, ...] | Literal[""] = ...,
        open: bool = ...,
        tags: str | list[str] | tuple[str, ...] = ...,
    ) -> None: ...
    def move(self, item: str | int, parent: str, index: int) -> None: ...
    def next(self, item: str | int) -> str: ...
    def parent(self, item: str | int) -> str: ...
    def prev(self, item: str | int) -> str: ...

    reattach = next

    def see(self, item: str | int) -> str: ...
    def selection(self) -> tuple[str, ...]: ...
    @overload
    def selection_add(
        self, items: list[str] | tuple[str, ...] | list[int] | tuple[int, ...], /
    ) -> None: ...
    @overload
    def selection_add(self, *items: str | int) -> None: ...
    @overload
    def selection_remove(
        self, items: list[str] | tuple[str, ...] | list[int] | tuple[int, ...], /
    ) -> None: ...
    @overload
    def selection_remove(self, *items: str | int) -> None: ...
    @overload
    def selection_set(
        self, items: list[str] | tuple[str, ...] | list[int] | tuple[int, ...], /
    ) -> None: ...
    @overload
    def selection_set(self, *items: str | int) -> None: ...
    @overload
    def selection_toggle(
        self, items: list[str] | tuple[str, ...] | list[int] | tuple[int, ...], /
    ) -> None: ...
    @overload
    def selection_toggle(self, *items: str | int) -> None: ...
    @overload
    def set(
        self, item: str | int, column: None = None, value: None = None
    ) -> dict[str, Any]: ...
    @overload
    def set(self, item: str | int, column: str | int, value: None = None) -> Any: ...
    @overload
    def set(self, item: str | int, column: str | int, value: Any) -> Literal[""]: ...
    def set_children(self, item: str | int, *newchildren: str | int) -> None: ...
    @overload
    def tag_bind(
        self,
        tagname: str,
        sequence: str | None = None,
        callback: Callable[[Event[CTkTreeview]], object] | None = None,
    ) -> str: ...
    @overload
    def tag_bind(self, tagname: str, sequence: str | None, callback: str) -> None: ...
    @overload
    def tag_bind(self, tagname: str, *, callback: str) -> None: ...
    @overload
    def tag_configure(
        self, tagname: str, option: Literal["foreground", "background"]
    ) -> str: ...
    @overload
    def tag_configure(
        self, tagname: str, option: Literal["font"]
    ) -> FontDescription: ...
    @overload
    def tag_configure(self, tagname: str, option: Literal["image"]) -> str: ...
    @overload
    def tag_configure(
        self,
        tagname: str,
        option: None = None,
        *,
        # There is also 'text' and 'anchor', but they don't seem to do anything, using them is likely a bug
        foreground: str = ...,
        background: str = ...,
        font: FontDescription = ...,
        image: ImageSpec = ...,
    ) -> _TreeviewTagDict | MaybeNone: ...  # can be None but annoying to check
    @overload
    def tag_has(self, tagname: str, item: None = None) -> tuple[str, ...]: ...
    @overload
    def tag_has(self, tagname: str, item: str | int) -> bool: ...
    @overload
    def xview(self) -> tuple[float, float]: ...
    @overload
    def xview(self, index: int) -> None: ...
    def xview_moveto(self, fraction: float) -> None: ...
    @overload
    def xview_scroll(self, number: int, what: Literal["units", "pages"]) -> None: ...
    @overload
    def xview_scroll(self, number: ScreenUnits, what: Literal["pixels"]) -> None: ...
    @overload
    def yview(self) -> tuple[float, float]: ...
    @overload
    def yview(self, index: int) -> None: ...
    def yview_moveto(self, fraction: float) -> None: ...
    @overload
    def yview_scroll(self, number: int, what: Literal["units", "pages"]) -> None: ...
    @overload
    def yview_scroll(self, number: ScreenUnits, what: Literal["pixels"]) -> None: ...

    ## Hooks

    def on_double_clicked(self, event: Event[Self]) -> None: ...
    def on_entry_focus_out(self, _event: Event[ctk.CTkEntry], **kw) -> None: ...
    def on_entry_enter_pressed(self, _event: Event, **kw) -> None: ...
